-- Gradebook column groups.
--
-- Column grouping is currently derived at render time: gradebookTable.tsx splits `slug` on "-",
-- special-cases `assignment-*`, and breaks a group whenever `sort_order` is not contiguous
-- (lines 2567-2589). The result exists only for the duration of a render and is copied across
-- four call sites, so there is nothing for an instructor to edit and no way to correct a
-- mis-grouped column.
--
-- This migration gives groups a row of their own, so membership becomes stored data rather than
-- a re-derived guess.

-- Part A: the groups themselves.
--
-- `class_id` is denormalized alongside `gradebook_id` on purpose: every RLS policy in this
-- schema authorizes against class_id (authorizeforclass / authorizeforclassinstructor), and
-- carrying it directly keeps those policies a single column read rather than a join back through
-- gradebooks. It matches how gradebook_columns already stores both. The accepted cost is that
-- the two columns could drift out of sync; that is not guarded here.
--
-- No uniqueness constraint on (gradebook_id, name) is declared here, because the backfill runs in
-- two phases and the first one needs duplicates to be legal. Today's heuristic produces two groups
-- with the same display name -- the seeded course shows "2 Quizzes..." twice, because sort_order 13
-- is missing -- so phase one reproduces that, and phase two merges it as a documented correction.
-- The constraint is added at the end of the backfill migration, once no duplicates remain, so the
-- merged state cannot regress.
create table public.gradebook_column_groups (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    class_id bigint not null references public.classes (id),
    gradebook_id bigint not null references public.gradebooks (id),
    name text not null,
    sort_order integer not null
);

comment on table public.gradebook_column_groups is
    'Named groups of gradebook columns. Replaces the render-time slug-prefix heuristic in gradebookTable.tsx.';
comment on column public.gradebook_column_groups.name is
    'Display label for the group header, e.g. "Labs". Editable by instructors.';
comment on column public.gradebook_column_groups.sort_order is
    'Left-to-right order of the group headers within a gradebook.';

create index idx_gradebook_column_groups_gradebook_id
    on public.gradebook_column_groups (gradebook_id);

-- Part B: membership.
--
-- Nullable, because "ungrouped" has to be a legal state. It is the state every existing column
-- is in the moment this statement runs, and it is where a column lands when its group is deleted.
--
-- ON DELETE SET NULL rather than CASCADE: deleting a group is a labelling action. Cascading would
-- take the columns with it, and gradebook_column_students rows hang off those columns, so a
-- mis-clicked "delete group" would destroy student scores. Clearing the label is recoverable;
-- deleting grades is not.
alter table public.gradebook_columns
    add column group_id bigint references public.gradebook_column_groups (id) on delete set null;

comment on column public.gradebook_columns.group_id is
    'Group this column is displayed under. NULL means ungrouped.';

create index idx_gradebook_columns_group_id
    on public.gradebook_columns (group_id);

-- Part C: row level security, mirroring the policies already on gradebook_columns
-- (20250614231720_gradebook.sql lines 649-662): instructors manage, everyone in the class reads.
alter table public.gradebook_column_groups enable row level security;

create policy "instructors CRUD"
on "public"."gradebook_column_groups"
as permissive
for all
to public
using (authorizeforclassinstructor(class_id));

-- The student-facing read is a deliberate mirror of the tightened gradebook_columns policy from
-- 20260407000000_gradebook_column_instructor_only.sql, not the simpler authorizeforclass() form.
-- That migration hid instructor-only columns from students until release; a group header is
-- derived from its members, so granting students a blanket read here would re-expose what that
-- migration hid -- a student would see a "Curve Adjustment" header with nothing under it and
-- learn the column exists. This database holds many courses at once, so the read rule is part of
-- the design rather than boilerplate.
--
-- Staff see every group. A student sees a group only when it holds at least one column that
-- student is allowed to see.
create policy "everyone in class can view"
on "public"."gradebook_column_groups"
as permissive
for select
to public
using (
  exists (
    select 1
    from public.user_privileges up
    where up.user_id = auth.uid()
      and up.class_id = gradebook_column_groups.class_id
  )
  and (
    exists (
      select 1
      from public.user_privileges up2
      where up2.user_id = auth.uid()
        and up2.class_id = gradebook_column_groups.class_id
        and up2.role in ('instructor', 'grader')
    )
    or exists (
      select 1
      from public.gradebook_columns gc
      where gc.group_id = gradebook_column_groups.id
        and (coalesce(gc.instructor_only, false) = false or gc.released = true)
    )
  )
);

-- Part D: the gradebook subscribes to realtime, so group edits need to reach open tabs the same
-- way column edits already do.
alter publication supabase_realtime add table public.gradebook_column_groups;
